blank_issues_enabled: false
contact_links:
  - name: Discord Accio Launcher
    url: https://discord.gg/TNwDQd7KGe
    about: Questions, aide et discussions. / Questions, help and chat.
  - name: Accio Launcher
    url: https://acciolauncher.be/
    about: Le launcher qui installe les jeux avec ce correctif. / The launcher that installs the games with this fix.
