# Accio Launcher - PC fix for the EA Harry Potter games.
# Copyright (c) 2026 Accio Launcher. PolyForm Strict 1.0.0, see license.
#
"""Writes source/winmm/winmm.def and source/winmm/exports.inc from Windows' 32-bit winmm.dll.

    python tools/make_winmm_exports.py

Once our winmm.dll is loaded, every DLL of the game's process that imports winmm.dll gets OURS
(Windows matches an already loaded module by name, and winmm is not a KnownDLL): it must export
every function the real one does, at the same ordinals, or such a DLL fails to load. The game
itself uses 16 of them (notes/HP2.md).

Run on Windows (it reads SysWOW64\\winmm.dll), commit the script and both files together. Not
run by the Build workflow: the list follows the Windows it is read on, and a newer Windows adding
a function costs nothing (no one in the game can import a name it does not know).
"""
from pathlib import Path

import pefile

# Written in C in winmm.cpp instead of jumping straight to Windows.
OWN = {"joyGetDevCapsA", "joyGetDevCapsW", "joyGetPosEx"}

LICENSE = ("Accio Launcher - PC fix for the EA Harry Potter games.",
           "Copyright (c) 2026 Accio Launcher. PolyForm Strict 1.0.0, see license.")
HEAD = ("".join(f"// {line}\r\n" for line in LICENSE) +
        "// Generated by tools/make_winmm_exports.py from Windows' 32-bit winmm.dll: do not edit.\r\n"
        "// X(index, ordinal, name) is jumped to straight away; OWN(...) is written in winmm.cpp.\r\n"
        "// NONAME(index, ordinal) has no name.\r\n")


def main():
    root = Path(__file__).resolve().parent.parent
    pe = pefile.PE(r"C:\Windows\SysWOW64\winmm.dll", fast_load=True)
    pe.parse_data_directories(directories=[pefile.DIRECTORY_ENTRY["IMAGE_DIRECTORY_ENTRY_EXPORT"]])
    symbols = sorted(pe.DIRECTORY_ENTRY_EXPORT.symbols, key=lambda s: s.ordinal)

    inc = [HEAD, f"#define ACCIO_WINMM_EXPORTS {len(symbols)}\r\n"]
    defs = [*(f"; {line}\r\n" for line in LICENSE), "LIBRARY winmm\r\n", "EXPORTS\r\n"]
    for index, s in enumerate(symbols):
        if s.forwarder:
            raise SystemExit(f"ordinal {s.ordinal} is forwarded: not handled")
        if s.name is None:
            inc.append(f"NONAME({index}, {s.ordinal})\r\n")
            defs.append(f"\tAccio_ordinal{s.ordinal} @{s.ordinal} NONAME\r\n")
            continue
        name = s.name.decode()
        inc.append(f"{'OWN' if name in OWN else 'X'}({index}, {s.ordinal}, {name})\r\n")
        defs.append(f"\t{name} = Accio_{name} @{s.ordinal}\r\n")

    missing = OWN - {s.name.decode() for s in symbols if s.name}
    if missing:
        raise SystemExit(f"not in winmm.dll: {', '.join(sorted(missing))}")
    folder = root / "source" / "winmm"
    (folder / "exports.inc").write_bytes("".join(inc).encode("ascii"))
    (folder / "winmm.def").write_bytes("".join(defs).encode("ascii"))
    print(len(symbols), "exports,", len(OWN), "written in C")


if __name__ == "__main__":
    main()
